spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  datasource2:
    name: demo
    url: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: JINGB
    password: JINGB
    driver-class-name: com.mysql.jdbc.Driver
    #使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat
      max-active: 20
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
  thymeleaf:
    prefix: /templates/
    suffix: .html
    cache: false
  profiles:
    active: test
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java,src/main/resources
      exclude: src/main/webapp
#配置包路径
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.example.demo.mysql.entity

#分页插件
pagehelper:
  auto-dialect:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql